# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pull-secret-updater
  namespace: pull-secret-updater
rules:
  # Needed to watch and load configuration and secret data.
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "update", "watch"]

  # This is needed by leader election to run the controller in HA.
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
