# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pull-secret-updater
rules:
  # Watch all Secrets.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

  # Update only certain Secrets.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["update"]
    resourceNames:
      - pull-secret

  # Allow creating events associated with resources we are controlling.
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
