# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pull-secret-updater
  namespace: pull-secret-updater
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: pull-secret-updater
roleRef:
  kind: Role
  name: pull-secret-updater
  apiGroup: rbac.authorization.k8s.io
