# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - uses: actions/checkout@v3

      - run: go test ./...

      - uses: ko-build/setup-ko@v0.6
      - env:
          KO_DOCKER_REPO: ghcr.io/imjasonh/pull-secret-updater/controller
        run: ko resolve -f ./config/ > ./release.yaml

      - uses: softprops/action-gh-release@v1
        with:
          files: release.yaml
